### ISSUE TITLE
Game crashes when starting the first run of a fresh profile

### ISSUE THREAD

**Issue by typhoonbro** [kjossul/NeowBlessings#4]
After creating a new profile, starting the first run the game crashes. If you alt+f4 and then start a new run, the crash doesn't happen. Probably related to the `unlock_card` or `discover_card` functions, based on the crash message. 

![image](https://github.com/kjossul/NeowBlessings/assets/40203414/dee5b715-8080-478f-b432-43eed44c1342)

**Comment by typhoonbro** [comment]
Awaiting review of [PR #5 ](https://github.com/kjossul/NeowBlessings/pull/5) with fix

**Comment by kjossul** [comment]
Merged and closed
